---
- hosts: '*'
  

  tasks:
  - name: Upgrade all packages
    apt:
        name: '*'
        state: latest
  - name: Remove useless packages that are no longer required
    apt:
        autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
        autoremove: yes
  - name: Reboot a slow machine that might have lots of updates to apply
    reboot:
        reboot_timeout: 3600
